{
 "title": "Open Telemetry out of the box",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Timing percentiles",
   "type": "stat",
   "description": "Estimated percentile values over a certain time interval",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, server_address) (rate(gen_ai_client_operation_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "100 {{server_address}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, server_address) (rate(gen_ai_client_operation_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99 {{server_address}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, server_address) (rate(gen_ai_client_operation_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "50 {{server_address}}"
    }
   ]
  },
  {
   "title": "Python GC objects collected change over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total[5m])",
     "legendFormat": "{{job}} GC objects collected total"
    }
   ]
  },
  {
   "title": "Component health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"fast-api-app\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{job=\"otel-collector\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Token in/out rate of change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(gen_ai_client_token_usage_tokens_sum{gen_ai_token_type=\"input\"}[5m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(rate(gen_ai_client_token_usage_tokens_sum{gen_ai_token_type=\"output\"}[5m]))",
     "legendFormat": "output"
    }
   ]
  }
 ]
}